name: Test
on: [push, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          name: mybuilder
      - name: Build and load Docker image (with timing)
        uses: docker/build-push-action@v5
        with:
          context: ./example
          file: ./example/Dockerfile
          load: true
          tags: testimage
      - name: Test the built image
        run: |
          docker run --rm testimage
